model:
  base_learning_rate: 4.5e-6
  target: vqgan.models.vqgan.VQModel
  params:
    embed_dim: 128
    n_embed: 2048
    ddconfig:
      double_z: False
      z_channels: 128
      resolution: 512
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [1,1,2,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 3
      attn_resolutions: [16]
      dropout: 0.0

    lossconfig:
      target: vqgan.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 3
        disc_start: 5000
        disc_weight: 0.8
        codebook_weight: 1.0

data:
  target: vqgan.datasets.dataloader.DataModuleFromConfig
  params:
    batch_size: 3  # 3 * 6 = 18
    num_workers: 18
    train:
      target: vqgan.datasets.cdip.CDIPTrain
      params:
        size: 512
    validation:
      target: vqgan.datasets.cdip.CDIPTest
      params:
        size: 512

